FROM python:3.12-slim

RUN apt-get update
RUN apt-get install -y ffmpeg libsndfile-dev build-essential cmake libedit-dev clang zlib1g-dev

WORKDIR /app

COPY ./heket/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./heket/*.py /app/
COPY ./heket/docker/run.sh /app/
RUN mkdir /app/models
COPY ./heket/models/* /app/models
RUN mkdir /app/web_assets
COPY ./heket/web_assets /app/web_assets

RUN chmod +x /app/*.sh

VOLUME ["/data"]

CMD ["/app/run.sh"]
